#!/bin/sh 
/bin/echo ""; 
/bin/echo "CHECKSUMS:"; 
/usr/bin/openssl dgst -blake2b512 /media/usb/localhost.apkovl.tar.gz; 
/usr/bin/openssl dgst -sha3-512 /media/usb/localhost.apkovl.tar.gz; 
/bin/echo ""; 
/bin/echo "SHA-512 checksum:"; 
/usr/bin/sha512sum /media/usb/localhost.apkovl.tar.gz; 
/bin/echo ""; 
/usr/bin/sha512sum -c /etc/files/512checksums.sha | /bin/grep -e FAILED -e WARNING; 
/sbin/apk verify /media/usb/cache/*.apk | /bin/grep UNTRUSTED; 
/sbin/apk verify /media/usb/apks/x86_64/*.apk | /bin/grep UNTRUSTED; 
/bin/echo ""; 
/sbin/ifconfig eth0 down; 
/usr/bin/macchanger -r eth0; 
/sbin/ifconfig eth0 up; 
/sbin/ifconfig wlan0 down; 
/usr/bin/macchanger -r wlan0; 
/sbin/ifconfig wlan0 up; 
/bin/echo ""; 
/bin/echo "Number of all files and folders on /media/usb:"; 
/usr/bin/find /media/usb/* | /usr/bin/wc -l;
/bin/echo ""; 
/bin/echo "Number of all files and folders in the following folders:"; 
/bin/echo "/media/usb/apks:"; 
/usr/bin/find /media/usb/apks | /usr/bin/wc -l; 
/bin/echo "/media/usb/boot:"; 
/usr/bin/find /media/usb/boot | /usr/bin/wc -l; 
/bin/echo "/media/usb/cache:"; 
/usr/bin/find /media/usb/cache | /usr/bin/wc -l; 
/bin/echo "/media/usb/SHARE:"; 
/usr/bin/find /media/usb/SHARE | /usr/bin/wc -l; 
/bin/cp -rp /etc/home/* /home/; 
/bin/rm -r /etc/home; 
/bin/mkdir /etc/home; 
/bin/chmod 600 /etc/home; 
/bin/chmod 400 /etc/motd; 
/bin/chown admin:admin /etc/motd; 
/bin/chown root:logcheck /var/log/messages; 
/bin/chmod 0700 /var/log/wtmp; 
/bin/chmod -s /bin/su; 
/bin/chmod -s /usr/bin/expiry; 
/bin/chmod -s /usr/bin/newgrp; 
/bin/chmod -s /usr/bin/gpasswd; 
/bin/chmod -s /usr/bin/chfn; 
/bin/chmod -s /usr/bin/chage; 
/bin/chmod -s /usr/bin/chsh; 
/bin/chmod 660 /dev/net/tun;
/bin/mkdir /var/log/audit; 
/bin/touch /var/log/audit/audit.log; 
/bin/chmod 640 /var/log/audit/audit.log; 
/bin/chmod 750 /var/log/audit; 
/bin/chown root:root /var/log/audit/audit.log; 
/bin/chown root:root /var/log/audit; 
/bin/mv /usr/bin/auvirt /usr/bin/ausyscall /usr/bin/aulastlog /usr/bin/aulast /sbin; 
/bin/mv /usr/sbin/autrace /usr/sbin/ausearch /usr/sbin/aureport /usr/sbin/augenrules /usr/sbin/auditd /usr/sbin/auditctl /usr/sbin/audisp-remote /usr/sbin/audispd /sbin;
/bin/echo ""; 
/sbin/rc-service auditd start;
